# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [218]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [219]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("./applicants_data.csv")

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [220]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [221]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(["EIN", "NAME"], axis= 1)

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [222]:
# Create a list of categorical variables 
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT", "SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [223]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse= False)

In [224]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [225]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns= enc.get_feature_names(categorical_variables)
    )

# Review the DataFrame
encoded_df

c:\Users\gbras\anaconda3\envs\dev\envs\dev\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [226]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
applicant_num_data_df = applicant_data_df.drop(categorical_variables, axis=1)

encoded_df = pd.concat([encoded_df, applicant_num_data_df], axis = 1)

# Review the Dataframe
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [272]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y

0             inf
1        2.000000
2        1.000000
3        1.000000
4        1.000000
           ...
34294    0.532455
34295    0.532439
34296    0.532424
34297    0.532437
34298    0.532422
Length: 34299, dtype: float64

In [228]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.iloc[:, :-1]

# Review the features DataFrame
X

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [229]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [230]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [231]:
# Define the the number of inputs (features) to the model
number_input_features = number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [232]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [233]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (number_input_features + 1) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [234]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [235]:
# Create the Sequential model instance
nn = Sequential()

In [236]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [237]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [238]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [239]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_49 (Dense)            (None, 58)                6786

 dense_50 (Dense)            (None, 29)                1711

 dense_51 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [240]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics="accuracy")

In [241]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train, y_train, epochs= 50)

Epoch 1/50
804/804 [==============================] - 1s 982us/step - loss: 34672.7109 - accuracy: 0.4946
Epoch 2/50
804/804 [==============================] - 1s 933us/step - loss: 59957.4648 - accuracy: 0.5014
Epoch 3/50
804/804 [==============================] - 1s 948us/step - loss: 59912.5039 - accuracy: 0.4966
Epoch 4/50
804/804 [==============================] - 1s 902us/step - loss: 37177.8906 - accuracy: 0.5024
Epoch 5/50
804/804 [==============================] - 1s 835us/step - loss: 36745.1992 - accuracy: 0.5045
Epoch 6/50
804/804 [==============================] - 1s 833us/step - loss: 1252.4442 - accuracy: 0.5220
Epoch 7/50
804/804 [==============================] - 1s 828us/step - loss: 28964.6895 - accuracy: 0.5198
Epoch 8/50
804/804 [==============================] - 1s 846us/step - loss: 12911.8877 - accuracy: 0.5033
Epoch 9/50
804/804 [==============================] - 1s 852us/step - loss: 45988.9180 - accuracy: 0.5156
Epoch 10/50
804/804 [==============================] - 1s 835us/step - loss: 7340.6230 - accuracy: 0.5184
Epoch 11/50
804/804 [==============================] - 1s 846us/step - loss: 6295.7349 - accuracy: 0.5210
Epoch 12/50
804/804 [==============================] - 1s 851us/step - loss: 16144.5557 - accuracy: 0.5077
Epoch 13/50
804/804 [==============================] - 1s 832us/step - loss: 7397.9600 - accuracy: 0.5180
Epoch 14/50
804/804 [==============================] - 1s 833us/step - loss: 6449.4331 - accuracy: 0.5250
Epoch 15/50
804/804 [==============================] - 1s 822us/step - loss: 9211.9932 - accuracy: 0.4966
Epoch 16/50
804/804 [==============================] - 1s 821us/step - loss: 4141.1338 - accuracy: 0.4986
Epoch 17/50
804/804 [==============================] - 1s 843us/step - loss: 2315.1951 - accuracy: 0.5070
Epoch 18/50
804/804 [==============================] - 1s 920us/step - loss: 694.3466 - accuracy: 0.5144
Epoch 19/50
804/804 [==============================] - 1s 824us/step - loss: 0.7079 - accuracy: 0.5639
Epoch 20/50
804/804 [==============================] - 1s 838us/step - loss: 0.6373 - accuracy: 0.6344
Epoch 21/50
804/804 [==============================] - 1s 828us/step - loss: 0.6316 - accuracy: 0.6468
Epoch 22/50
804/804 [==============================] - 1s 835us/step - loss: 0.6238 - accuracy: 0.6636
Epoch 23/50
804/804 [==============================] - 1s 845us/step - loss: 0.6293 - accuracy: 0.6545
Epoch 24/50
804/804 [==============================] - 1s 939us/step - loss: 0.6232 - accuracy: 0.6643
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6772 - accuracy: 0.5524
Epoch 26/50
804/804 [==============================] - 1s 864us/step - loss: 0.6398 - accuracy: 0.6268
Epoch 27/50
804/804 [==============================] - 1s 848us/step - loss: 0.6254 - accuracy: 0.6604
Epoch 28/50
804/804 [==============================] - 1s 957us/step - loss: 0.6722 - accuracy: 0.5723
Epoch 29/50
804/804 [==============================] - 1s 987us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 30/50
804/804 [==============================] - 1s 909us/step - loss: 0.6909 - accuracy: 0.5335
Epoch 31/50
804/804 [==============================] - 1s 884us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 32/50
804/804 [==============================] - 1s 891us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 33/50
804/804 [==============================] - 1s 846us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 34/50
804/804 [==============================] - 1s 879us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 35/50
804/804 [==============================] - 1s 960us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 36/50
804/804 [==============================] - 1s 997us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 37/50
804/804 [==============================] - 1s 917us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 38/50
804/804 [==============================] - 1s 899us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 39/50
804/804 [==============================] - 1s 970us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6911 - accuracy: 0.5335
Epoch 41/50
804/804 [==============================] - 1s 904us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 42/50
804/804 [==============================] - 1s 821us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 43/50
804/804 [==============================] - 1s 830us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 44/50
804/804 [==============================] - 1s 812us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 45/50
804/804 [==============================] - 1s 808us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 46/50
804/804 [==============================] - 1s 805us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 47/50
804/804 [==============================] - 1s 828us/step - loss: 0.6911 - accuracy: 0.5335
Epoch 48/50
804/804 [==============================] - 1s 992us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 49/50
804/804 [==============================] - 1s 934us/step - loss: 0.6910 - accuracy: 0.5335
Epoch 50/50
804/804 [==============================] - 1s 920us/step - loss: 0.6911 - accuracy: 0.5335

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [242]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 1.7107 - accuracy: 0.5523 - 252ms/epoch - 940us/step
Loss: 1.7106866836547852, Accuracy: 0.5523031949996948

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [243]:
# Set the model's file path
file_path = Path('./applicants_data.h5')

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [244]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [245]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [246]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = int((number_input_features + 1) * 2/3)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

78

In [247]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [248]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim= number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units= 1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_52 (Dense)            (None, 78)                9126

 dense_53 (Dense)            (None, 1)                 79

=================================================================
Total params: 9,205
Trainable params: 9,205
Non-trainable params: 0
_________________________________________________________________

In [249]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics="accuracy")

In [250]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 39328.4492 - accuracy: 0.5020
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 29962.1250 - accuracy: 0.5002
Epoch 3/50
804/804 [==============================] - 1s 987us/step - loss: 7527.4414 - accuracy: 0.5033
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 36648.5664 - accuracy: 0.4964
Epoch 5/50
804/804 [==============================] - 1s 905us/step - loss: 30994.7422 - accuracy: 0.5104
Epoch 6/50
804/804 [==============================] - 1s 857us/step - loss: 44446.2891 - accuracy: 0.5328
Epoch 7/50
804/804 [==============================] - 1s 951us/step - loss: 29786.0645 - accuracy: 0.5309
Epoch 8/50
804/804 [==============================] - 1s 851us/step - loss: 21182.9297 - accuracy: 0.5075
Epoch 9/50
804/804 [==============================] - 1s 929us/step - loss: 38882.7109 - accuracy: 0.5326
Epoch 10/50
804/804 [==============================] - 1s 917us/step - loss: 33641.5625 - accuracy: 0.5560
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 32061.7109 - accuracy: 0.5383
Epoch 12/50
804/804 [==============================] - 1s 826us/step - loss: 16009.1777 - accuracy: 0.5792
Epoch 13/50
804/804 [==============================] - 1s 786us/step - loss: 34949.2109 - accuracy: 0.5290
Epoch 14/50
804/804 [==============================] - 1s 791us/step - loss: 19141.2148 - accuracy: 0.5355
Epoch 15/50
804/804 [==============================] - 1s 820us/step - loss: 37005.1523 - accuracy: 0.5359
Epoch 16/50
804/804 [==============================] - 1s 839us/step - loss: 8093.9209 - accuracy: 0.5369
Epoch 17/50
804/804 [==============================] - 1s 830us/step - loss: 37677.3047 - accuracy: 0.5595
Epoch 18/50
804/804 [==============================] - 1s 821us/step - loss: 14840.9434 - accuracy: 0.5780
Epoch 19/50
804/804 [==============================] - 1s 814us/step - loss: 5272.6709 - accuracy: 0.5897
Epoch 20/50
804/804 [==============================] - 1s 806us/step - loss: 4768.9604 - accuracy: 0.5728
Epoch 21/50
804/804 [==============================] - 1s 808us/step - loss: 21505.0430 - accuracy: 0.5189
Epoch 22/50
804/804 [==============================] - 1s 807us/step - loss: 27910.3398 - accuracy: 0.5369
Epoch 23/50
804/804 [==============================] - 1s 805us/step - loss: 7639.9360 - accuracy: 0.5800
Epoch 24/50
804/804 [==============================] - 1s 812us/step - loss: 16544.0820 - accuracy: 0.5868
Epoch 25/50
804/804 [==============================] - 1s 801us/step - loss: 27602.0977 - accuracy: 0.5135
Epoch 26/50
804/804 [==============================] - 1s 818us/step - loss: 20437.6758 - accuracy: 0.5687
Epoch 27/50
804/804 [==============================] - 1s 788us/step - loss: 1548.9866 - accuracy: 0.6288
Epoch 28/50
804/804 [==============================] - 1s 801us/step - loss: 21289.5059 - accuracy: 0.5189
Epoch 29/50
804/804 [==============================] - 1s 798us/step - loss: 15635.7646 - accuracy: 0.5859
Epoch 30/50
804/804 [==============================] - 1s 792us/step - loss: 10955.3242 - accuracy: 0.6127
Epoch 31/50
804/804 [==============================] - 1s 816us/step - loss: 14115.2041 - accuracy: 0.5549
Epoch 32/50
804/804 [==============================] - 1s 793us/step - loss: 7348.1060 - accuracy: 0.5456
Epoch 33/50
804/804 [==============================] - 1s 798us/step - loss: 4162.9409 - accuracy: 0.5673
Epoch 34/50
804/804 [==============================] - 1s 797us/step - loss: 3616.6677 - accuracy: 0.6067
Epoch 35/50
804/804 [==============================] - 1s 795us/step - loss: 13197.9023 - accuracy: 0.5286
Epoch 36/50
804/804 [==============================] - 1s 816us/step - loss: 5915.0308 - accuracy: 0.5337
Epoch 37/50
804/804 [==============================] - 1s 801us/step - loss: 15237.0117 - accuracy: 0.5448
Epoch 38/50
804/804 [==============================] - 1s 796us/step - loss: 2219.5537 - accuracy: 0.5970
Epoch 39/50
804/804 [==============================] - 1s 807us/step - loss: 13225.9961 - accuracy: 0.5390
Epoch 40/50
804/804 [==============================] - 1s 886us/step - loss: 3415.8186 - accuracy: 0.6207
Epoch 41/50
804/804 [==============================] - 1s 925us/step - loss: 10184.3389 - accuracy: 0.5868
Epoch 42/50
804/804 [==============================] - 1s 871us/step - loss: 3822.2251 - accuracy: 0.6035
Epoch 43/50
804/804 [==============================] - 1s 831us/step - loss: 4983.6963 - accuracy: 0.5441
Epoch 44/50
804/804 [==============================] - 1s 806us/step - loss: 18546.3750 - accuracy: 0.5647
Epoch 45/50
804/804 [==============================] - 1s 803us/step - loss: 2919.1755 - accuracy: 0.5725
Epoch 46/50
804/804 [==============================] - 1s 795us/step - loss: 7998.0288 - accuracy: 0.5770
Epoch 47/50
804/804 [==============================] - 1s 781us/step - loss: 9877.9336 - accuracy: 0.5877
Epoch 48/50
804/804 [==============================] - 1s 787us/step - loss: 1199.5674 - accuracy: 0.6170
Epoch 49/50
804/804 [==============================] - 1s 810us/step - loss: 8402.0244 - accuracy: 0.5638
Epoch 50/50
804/804 [==============================] - 1s 799us/step - loss: 4909.7041 - accuracy: 0.5474

#### Alternative Model 2

In [251]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [252]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [253]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1)//2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [254]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A2 + 1)//2

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

29

In [255]:
# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A2 = (hidden_nodes_layer2_A2 + 1)//2

# Review the number of hidden nodes in the third layer
hidden_nodes_layer3_A2

15

In [256]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [257]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="elu"))

# Second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer2_A2, activation="elu"))

# Third hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer3_A2, activation="elu"))

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_54 (Dense)            (None, 58)                6786

 dense_55 (Dense)            (None, 29)                1711

 dense_56 (Dense)            (None, 15)                450

 dense_57 (Dense)            (None, 1)                 16

=================================================================
Total params: 8,963
Trainable params: 8,963
Non-trainable params: 0
_________________________________________________________________

In [258]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics="accuracy")

In [259]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train, y_train, epochs= 50)

Epoch 1/50
804/804 [==============================] - 1s 893us/step - loss: 6012.0132 - accuracy: 0.4946
Epoch 2/50
804/804 [==============================] - 1s 891us/step - loss: 6789.5698 - accuracy: 0.4920
Epoch 3/50
804/804 [==============================] - 1s 897us/step - loss: 4080.1511 - accuracy: 0.4981
Epoch 4/50
804/804 [==============================] - 1s 904us/step - loss: 7266.1973 - accuracy: 0.5069
Epoch 5/50
804/804 [==============================] - 1s 896us/step - loss: 8589.6250 - accuracy: 0.4936
Epoch 6/50
804/804 [==============================] - 1s 892us/step - loss: 3930.8499 - accuracy: 0.5027
Epoch 7/50
804/804 [==============================] - 1s 892us/step - loss: 427.6104 - accuracy: 0.5099
Epoch 8/50
804/804 [==============================] - 1s 888us/step - loss: 4210.9033 - accuracy: 0.4954
Epoch 9/50
804/804 [==============================] - 1s 899us/step - loss: 127.5224 - accuracy: 0.5266
Epoch 10/50
804/804 [==============================] - 1s 901us/step - loss: 0.6921 - accuracy: 0.5277
Epoch 11/50
804/804 [==============================] - 1s 896us/step - loss: 0.6916 - accuracy: 0.5301
Epoch 12/50
804/804 [==============================] - 1s 896us/step - loss: 0.6917 - accuracy: 0.5335
Epoch 13/50
804/804 [==============================] - 1s 881us/step - loss: 0.6918 - accuracy: 0.5299
Epoch 14/50
804/804 [==============================] - 1s 886us/step - loss: 0.6919 - accuracy: 0.5276
Epoch 15/50
804/804 [==============================] - 1s 869us/step - loss: 0.6916 - accuracy: 0.5314
Epoch 16/50
804/804 [==============================] - 1s 874us/step - loss: 0.6922 - accuracy: 0.5248
Epoch 17/50
804/804 [==============================] - 1s 881us/step - loss: 0.6919 - accuracy: 0.5289
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6919 - accuracy: 0.5297
Epoch 19/50
804/804 [==============================] - 1s 945us/step - loss: 0.6918 - accuracy: 0.5305
Epoch 20/50
804/804 [==============================] - 1s 904us/step - loss: 0.6920 - accuracy: 0.5259
Epoch 21/50
804/804 [==============================] - 1s 930us/step - loss: 0.6921 - accuracy: 0.5271
Epoch 22/50
804/804 [==============================] - 1s 955us/step - loss: 0.6920 - accuracy: 0.5266
Epoch 23/50
804/804 [==============================] - 1s 876us/step - loss: 0.6922 - accuracy: 0.5262
Epoch 24/50
804/804 [==============================] - 1s 963us/step - loss: 0.6925 - accuracy: 0.5269
Epoch 25/50
804/804 [==============================] - 1s 923us/step - loss: 0.6921 - accuracy: 0.5283
Epoch 26/50
804/804 [==============================] - 1s 973us/step - loss: 0.6585 - accuracy: 0.6035
Epoch 27/50
804/804 [==============================] - 1s 931us/step - loss: 0.6397 - accuracy: 0.6443
Epoch 28/50
804/804 [==============================] - 1s 958us/step - loss: 0.6425 - accuracy: 0.6389
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6793 - accuracy: 0.5550
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6925 - accuracy: 0.5294
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6927 - accuracy: 0.5269
Epoch 32/50
804/804 [==============================] - 1s 922us/step - loss: 0.6929 - accuracy: 0.5252
Epoch 33/50
804/804 [==============================] - 1s 922us/step - loss: 0.6939 - accuracy: 0.5216
Epoch 34/50
804/804 [==============================] - 1s 956us/step - loss: 0.6934 - accuracy: 0.5211
Epoch 35/50
804/804 [==============================] - 1s 942us/step - loss: 0.6933 - accuracy: 0.5227
Epoch 36/50
804/804 [==============================] - 1s 942us/step - loss: 0.6929 - accuracy: 0.5247
Epoch 37/50
804/804 [==============================] - 1s 940us/step - loss: 0.6938 - accuracy: 0.5198
Epoch 38/50
804/804 [==============================] - 1s 934us/step - loss: 0.6929 - accuracy: 0.5266
Epoch 39/50
804/804 [==============================] - 1s 917us/step - loss: 0.6930 - accuracy: 0.5234
Epoch 40/50
804/804 [==============================] - 1s 940us/step - loss: 0.6933 - accuracy: 0.5230
Epoch 41/50
804/804 [==============================] - 1s 918us/step - loss: 0.6930 - accuracy: 0.5215
Epoch 42/50
804/804 [==============================] - 1s 934us/step - loss: 0.6938 - accuracy: 0.5213
Epoch 43/50
804/804 [==============================] - 1s 916us/step - loss: 0.6931 - accuracy: 0.5206
Epoch 44/50
804/804 [==============================] - 1s 921us/step - loss: 0.6927 - accuracy: 0.5250
Epoch 45/50
804/804 [==============================] - 1s 914us/step - loss: 0.6930 - accuracy: 0.5213
Epoch 46/50
804/804 [==============================] - 1s 907us/step - loss: 0.6941 - accuracy: 0.5186
Epoch 47/50
804/804 [==============================] - 1s 907us/step - loss: 0.6945 - accuracy: 0.5210
Epoch 48/50
804/804 [==============================] - 1s 905us/step - loss: 0.6934 - accuracy: 0.5221
Epoch 49/50
804/804 [==============================] - 1s 897us/step - loss: 0.6933 - accuracy: 0.5237
Epoch 50/50
804/804 [==============================] - 1s 910us/step - loss: 0.6926 - accuracy: 0.5252

#### Alternative Model 3

In [260]:
# Define the the number of inputs (features) to the model
X_train_pruned = X_train.drop(["SPECIAL_CONSIDERATIONS_N", "SPECIAL_CONSIDERATIONS_Y", "STATUS"], axis=1)

number_input_features = len(X_train_pruned.iloc[0])

# Review the number of features
number_input_features

113

In [261]:
# Define the number of neurons in the output layer
number_output_neurons_A3 = 1

In [262]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A3 = int((number_input_features + 1)*2/3)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A3

76

In [263]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A3 = int((hidden_nodes_layer1_A3 + 1)*2/3)

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A3

51

In [264]:
# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A3 = (hidden_nodes_layer2_A3 + 1)//2

# Review the number of hidden nodes in the third layer
hidden_nodes_layer3_A3

26

In [265]:
# Create the Sequential model instance
nn_A3 = Sequential()

In [266]:
# First hidden layer
nn_A3.add(Dense(units=hidden_nodes_layer1_A3, input_dim=number_input_features, activation="elu"))

# Second hidden layer
nn_A3.add(Dense(units=hidden_nodes_layer2_A3, activation="elu"))

# Third hidden layer
nn_A3.add(Dense(units=hidden_nodes_layer3_A3, activation="elu"))

# Output layer
nn_A3.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A3.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_58 (Dense)            (None, 76)                8664

 dense_59 (Dense)            (None, 51)                3927

 dense_60 (Dense)            (None, 26)                1352

 dense_61 (Dense)            (None, 1)                 27

=================================================================
Total params: 13,970
Trainable params: 13,970
Non-trainable params: 0
_________________________________________________________________

In [267]:
# Compile the model
nn_A3.compile(loss="binary_crossentropy", optimizer="adam", metrics="accuracy")

In [270]:
# Fit the model
fit_model_A3 = nn_A3.fit(X_train_pruned, y_train, epochs= 50)

Epoch 1/50
804/804 [==============================] - 1s 971us/step - loss: 0.6942 - accuracy: 0.5199
Epoch 2/50
804/804 [==============================] - 1s 954us/step - loss: 0.6947 - accuracy: 0.5206
Epoch 3/50
804/804 [==============================] - 1s 940us/step - loss: 0.6934 - accuracy: 0.5236
Epoch 4/50
804/804 [==============================] - 1s 930us/step - loss: 0.6947 - accuracy: 0.5206
Epoch 5/50
804/804 [==============================] - 1s 937us/step - loss: 0.6944 - accuracy: 0.5206
Epoch 6/50
804/804 [==============================] - 1s 952us/step - loss: 0.6940 - accuracy: 0.5217
Epoch 7/50
804/804 [==============================] - 1s 949us/step - loss: 0.6947 - accuracy: 0.5192
Epoch 8/50
804/804 [==============================] - 1s 939us/step - loss: 0.6948 - accuracy: 0.5195
Epoch 9/50
804/804 [==============================] - 1s 943us/step - loss: 0.6934 - accuracy: 0.5204
Epoch 10/50
804/804 [==============================] - 1s 952us/step - loss: 0.6956 - accuracy: 0.5168
Epoch 11/50
804/804 [==============================] - 1s 977us/step - loss: 0.6935 - accuracy: 0.5224
Epoch 12/50
804/804 [==============================] - 1s 944us/step - loss: 0.6936 - accuracy: 0.5185
Epoch 13/50
804/804 [==============================] - 1s 948us/step - loss: 0.6934 - accuracy: 0.5196
Epoch 14/50
804/804 [==============================] - 1s 935us/step - loss: 0.6942 - accuracy: 0.5196
Epoch 15/50
804/804 [==============================] - 1s 960us/step - loss: 0.6933 - accuracy: 0.5205
Epoch 16/50
804/804 [==============================] - 1s 939us/step - loss: 0.6936 - accuracy: 0.5201
Epoch 17/50
804/804 [==============================] - 1s 928us/step - loss: 0.6937 - accuracy: 0.5208
Epoch 18/50
804/804 [==============================] - 1s 938us/step - loss: 0.6931 - accuracy: 0.5211
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6935 - accuracy: 0.5224
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6931 - accuracy: 0.5221
Epoch 21/50
804/804 [==============================] - 1s 960us/step - loss: 0.6929 - accuracy: 0.5241
Epoch 22/50
804/804 [==============================] - 1s 958us/step - loss: 0.6936 - accuracy: 0.5181
Epoch 23/50
804/804 [==============================] - 1s 952us/step - loss: 0.6933 - accuracy: 0.5245
Epoch 24/50
804/804 [==============================] - 1s 956us/step - loss: 0.6931 - accuracy: 0.5237
Epoch 25/50
804/804 [==============================] - 1s 975us/step - loss: 0.6932 - accuracy: 0.5238
Epoch 26/50
804/804 [==============================] - 1s 965us/step - loss: 0.6936 - accuracy: 0.5216
Epoch 27/50
804/804 [==============================] - 1s 968us/step - loss: 0.6932 - accuracy: 0.5225
Epoch 28/50
804/804 [==============================] - 1s 959us/step - loss: 0.6922 - accuracy: 0.5251
Epoch 29/50
804/804 [==============================] - 1s 960us/step - loss: 0.6933 - accuracy: 0.5224
Epoch 30/50
804/804 [==============================] - 1s 967us/step - loss: 0.6929 - accuracy: 0.5249
Epoch 31/50
804/804 [==============================] - 1s 990us/step - loss: 0.6933 - accuracy: 0.5248
Epoch 32/50
804/804 [==============================] - 1s 973us/step - loss: 0.6929 - accuracy: 0.5218
Epoch 33/50
804/804 [==============================] - 1s 950us/step - loss: 0.6931 - accuracy: 0.5192
Epoch 34/50
804/804 [==============================] - 1s 964us/step - loss: 0.6927 - accuracy: 0.5266
Epoch 35/50
804/804 [==============================] - 1s 962us/step - loss: 0.6924 - accuracy: 0.5262
Epoch 36/50
804/804 [==============================] - 1s 979us/step - loss: 0.6930 - accuracy: 0.5246
Epoch 37/50
804/804 [==============================] - 1s 958us/step - loss: 0.6931 - accuracy: 0.5251
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6927 - accuracy: 0.5254
Epoch 39/50
804/804 [==============================] - 1s 989us/step - loss: 0.6934 - accuracy: 0.5207
Epoch 40/50
804/804 [==============================] - 1s 959us/step - loss: 0.6928 - accuracy: 0.5226
Epoch 41/50
804/804 [==============================] - 1s 959us/step - loss: 0.6928 - accuracy: 0.5274
Epoch 42/50
804/804 [==============================] - 1s 958us/step - loss: 0.6931 - accuracy: 0.5250
Epoch 43/50
804/804 [==============================] - 1s 955us/step - loss: 0.6927 - accuracy: 0.5257
Epoch 44/50
804/804 [==============================] - 1s 976us/step - loss: 0.6937 - accuracy: 0.5208
Epoch 45/50
804/804 [==============================] - 1s 960us/step - loss: 0.6929 - accuracy: 0.5210
Epoch 46/50
804/804 [==============================] - 1s 974us/step - loss: 0.6927 - accuracy: 0.5262
Epoch 47/50
804/804 [==============================] - 1s 965us/step - loss: 0.6930 - accuracy: 0.5223
Epoch 48/50
804/804 [==============================] - 1s 972us/step - loss: 0.6926 - accuracy: 0.5234
Epoch 49/50
804/804 [==============================] - 1s 970us/step - loss: 0.6930 - accuracy: 0.5189
Epoch 50/50
804/804 [==============================] - 1s 969us/step - loss: 0.6930 - accuracy: 0.5253

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [274]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.6917 - accuracy: 0.5292 - 732ms/epoch - 3ms/step
Loss: 0.6916702389717102, Accuracy: 0.5292128324508667

In [275]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 2967.7051 - accuracy: 0.4828 - 343ms/epoch - 1ms/step
Loss: 2967.705078125, Accuracy: 0.48279884457588196

In [276]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.6917 - accuracy: 0.5292 - 338ms/epoch - 1ms/step
Loss: 0.6917241811752319, Accuracy: 0.5292128324508667

In [281]:
print("Alternative Model 3 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
X_test_pruned = X_test.drop(["SPECIAL_CONSIDERATIONS_N", "SPECIAL_CONSIDERATIONS_Y", "STATUS"], axis=1)

model_loss, model_accuracy = nn_A3.evaluate(X_test_pruned, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 3 Results
268/268 - 0s - loss: 0.6916 - accuracy: 0.5292 - 299ms/epoch - 1ms/step
Loss: 0.6915723085403442, Accuracy: 0.5292128324508667

### Step 3: Save each of your alternative models as an HDF5 file.

In [282]:
# Set the file path for the first alternative model
file_path = Path('./applicants_data_A1.h5')

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [283]:
# Set the file path for the second alternative model
file_path = Path('./applicants_data_A2.h5')

# Export your model to a HDF5 file
nn_A2.save(file_path)

In [284]:
# Set the file path for the second alternative model
file_path = Path('./applicants_data_A3.h5')

# Export your model to a HDF5 file
nn_A3.save(file_path)